Plant-for-the-Planet-org/planet-donations

package-lock.json
package.json

- keep next-i18next fixed to version 8.4.0 to avoid not loading all resources in the Frontend (not working on version 8.8.0)

fix broken language support

---

src/Donations/Micros/DonationTypes/BouquetDonations.tsx

Changes to fix errors in Bouquet donations process:
- allow to enter decimal numbers (replace "," with "." as we have not i18n number parser)
- do not apply paymentSetup.unitCost any more on quantity
To-Do:

Fixes for Bouquet donation process

---

package-lock.json
package.json
src/Donations/Components/PaymentsForm.tsx

Fixes problem not being able to finish donation e.g. with PayPal for logged in user of native Treecounter-App:
- use the token given by the queryToken parameter
- upgraded PayPal module (not necessary for the bugfix)
Test requires using Treecounter app with a logged in user and donate e.g. with PayPal.

fix Treecounter donations with PayPal

---

src/Donations/PaymentMethods/PaymentFunctions.ts
src/Layout/QueryParamContext.tsx
src/Utils/api.ts

Changes
- pass frequency 'once' for one-time donation
- added locale in query param instead of headers in all API calls

Locale in query params

---

src/Donations/PaymentMethods/NewPaypal.tsx

PayPal processing: disable the following funding options: giropay, sofort, sepa (We already support these payment methods through Stripe with lower transaction fees)
Fixes #
Check this list and then dismiss it:
- disable the following funding options: giropay, sofort, sepa
@

PayPal processing: Disable duplicate payment gateways

---

pages/index.tsx
src/Donations/index.tsx
src/Layout/Footer.tsx

Changes in this PR:
- Fixed language bug
- replace Next image with HTML img tag for planet logo in Footer
- skipped Default forest image loading unnecessarily
How to reproduce language bug:
- Refresh on donate step 2-3 time and check name and description.
- Also, Go to the payments step, paymentOptions API will be called again and the description will be set in English by default

Fixed translation bug

---

src/Donations/Components/DonationsForm.tsx

Fixes #250
- check for res given before trying to pay donation
This does not make the error message better if the last name from Google Pay is missing, but just avoids a crash.

Avoid crash for missing lastname from Google Pay

---

src/Utils/browsercheck.ts

Fixes Slack Request
- don't do the browser check for Safari on Android devices

don't do the browser check for Safari on Android devices

---

src/Donations/Components/SelectProject.tsx

Fixes client side error due to null value received for tpo name in the `/projects` response

fix: fix crash due to null tpo name for project

---

README.md

Whenever Markdown and HTML is mixed, Github needs a blank line to switch back to Markdown mode. With this new line, the Markdown link is recognized.

Readme: Fix link

---

src/Donations/Components/DonationsForm.tsx
src/Donations/PaymentMethods/PaymentFunctions.ts

`recipientName` is an invalid field while creating `direct-gift` donations. While creating donations with payment method PlanetCash, `recipientName` was being passed for both `direct-gift` and `invitation-gift` donations, resulting in a validation error response from `POST app/donations`. This fix resolves that issue. 
It also removes `message` from `direct-gift` donations as the value contained is always blank.

fix: resolve extra field error for direct gifts

---

package-lock.json
src/Layout/QueryParamContext.tsx

When user tries to add an invalid locale as a parameter, the user is directed to the default value based on the browser location. If still not supported by us, the value is set to 'en'.

replace invalid locale with default value 

---

src/Common/Types/index.tsx
src/Donations/Micros/SelectCurrencyModal.tsx
src/Layout/QueryParamContext.tsx
src/Utils/countriesData.json
src/Utils/countryUtils.ts

1. Fixes https://github.com/Plant-for-the-Planet-org/planet-webapp/issues/773
2. Fetches supported currencies by API (~~Note - API will be replaced by a new API with a similar response format, to be updated once the API is available~~) and filters list of currencies available while making a donation (in the donate step), removing unsupported currencies from the currency selector.
3. Adds fallback to Euros if an invalid currency is somehow selected (e.g. if you provide ?country=AQ in the URL).  
4. Also includes some code cleanup.

Disable unsupported payment currencies

---

public/locales/de/common.json
public/locales/en/common.json
public/locales/es/common.json
src/Donations/PaymentMethods/NewPaypal.tsx

Adds an error message for paypal payment errors, guiding user to use other payment methods

fix: add paypal error message with translations

---

src/Utils/countriesData.json

Update Croatian currency to Euros. To be released on January 1, 2023 when Croatia joins the Eurozone and the Croatian Kuna (HRK) is deprecated in favor of the Euro.

Update Croatian currency to Euros

---

src/Utils/countriesData.json

Updates Croatian currency to Euros to prepare for deprecation of HRK when Croatia joins the Eurozone

Release: Update Croatian currency to Euro (1st Jan 2023)

---

package-lock.json
package.json
src/Common/InputTypes/MaterialTextField.tsx
src/Donations/Components/ContactsForm.tsx
src/Donations/Micros/Authentication.tsx
src/Donations/Micros/GiftForm.tsx
src/Donations/Micros/OnBehalf.tsx
src/Layout/QueryParamContext.tsx

Updates react-hook-form from v6.14 to v7.43, as v is not compatible with React 18 (needed for upgrade to Next 13)
1. Updates dependency for React Hook Form
2. Replaces use of `register` with `Controller` wrapper around MUI input components
3. Minor changes to resolve warnings while populating contact form details
4. Minor change to multi line message field in GiftForm to add min/max row restrictions

Upgrade react hook form to v7 (for next 13 update)

---

package-lock.json
package.json
pages/_app.tsx
pages/_document.tsx
src/Common/ContentLoaders/Donations/PaymentProgress.tsx
src/Common/InputTypes/AutoCompleteCountry.tsx
src/Common/InputTypes/CheckBox.tsx
src/Common/InputTypes/GreenRadio.tsx
src/Common/InputTypes/MaterialTextField.tsx
src/Common/InputTypes/ToggleSwitch.tsx
src/Donations/Components/ContactsForm.tsx
src/Donations/Components/DonationsForm.tsx
src/Donations/Components/PaymentStatus.tsx
src/Donations/Micros/Authentication.tsx
src/Donations/Micros/GiftForm.tsx
src/Donations/Micros/OnBehalf.tsx
src/Donations/Micros/PlanetCashSignup.tsx
src/Donations/Micros/SelectCurrencyModal.tsx
src/Donations/Micros/TaxDeductionCountryModal.tsx
src/Donations/PaymentMethods/CardPayments.tsx
src/Donations/PaymentMethods/SepaPayments.tsx
src/Layout/Footer.tsx
src/Layout/QueryParamContext.tsx
styles/createEmotionCache.ts
styles/muiTheme.ts

Updates MUI from v4.11 to v5.11, as v4.11 is not compatible with React 18 (needed for upgrade to Next 13)
Updates react-hook-form from v6.14 to v7.43, as v is not compatible with React 18 (needed for upgrade to Next 13)
MUI
- Updates dependencies for MUI and removes deprecated dependencies
- replaces ServerStyleSheets with EmotionCache for SSR support
- updates imports and adapts used MUI components if needed
- removes instances of withStyles / makeStyles and replaces with styled() if needed
React Hook Form (merged from #383)
- Updates dependency for React Hook Form
- Replaces use of register with Controller wrapper around MUI input components
- Minor changes to resolve warnings while populating contact form details
- Minor change to multi line message field …

Upgrade mui version and react-hook-forms (for next 13 update)

---

public/locales/en/common.json
src/Donations/Components/ContactsForm.tsx
src/Donations/Micros/Authentication.tsx

1. `isCompany` toggle is shown only for guest users
2. `companyName` field can only be shown for guest/non-individual users
3. `companyName` is populated and not editable for non-individual users

Restricts display of company name / toggle

---

src/Donations/Components/PaymentsForm.tsx

On retrying payment after a failed donation, the user would get stuck on the "Seeding your donation" loader. This has been resolved. 
NOTE: should be merged to develop only after #387.

Fixes payment retry issue where user got stuck on "Seeding your donation"

---

src/Donations/Components/ContactsForm.tsx

When a user is logged in on the webapp and selects a project to donate to, they are able to edit the email that is within the contact details. This should not be possible, like it is not when you directly log in on donate.

Disable email field in contact form

---

src/Donations/Components/DonationsForm.tsx
src/Donations/PaymentMethods/PaymentMethodTabs.tsx
src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx

As there are double charging issues seen in Apple pay, native payment options are disabled until a fix is found.

Temporarily disable native payment options

---

src/Donations/LeftPanel/LeftPanelInfo.tsx
src/Donations/PaymentMethods/PaymentFunctions.ts

When topping up PlanetCash sending giftData will result in an error “extra field”. This is the case for direct as well as invitation gifts.
This PR focuses on removing the additional `gift` field that was being sent in the request

Ensure that no giftData is sent to backend when topping up PlanetCash

---

src/Donations/Components/ContactsForm.tsx

Fixes a bug that set `welcomePackageStatus = draft` even when user was not eligible for welcome package (i.e. invalid project and/or country).
Ensures that `isPackageWanted` within `QueryParamContext` remains null if not eligible for package

Sends `welcomePackageStatus = draft` only when eligible

---

src/Donations/Components/DonationsForm.tsx

If the project does not support tax deductions for `planetCash.country`, planet cash is removed as a payment option. This is in addition to the previous restrictions on planet cash payments.
**Examples**
https://donate-with-planet-oex50iyns-planetapp.vercel.app/?to=accion-andina-andes-action&step=donate - Acción Andina - Only supports planet cash donations for US/DE planet cash accounts.
https://donate-with-planet-oex50iyns-planetapp.vercel.app/?to=plant-for-ghana&step=donate - Plant-for-the-Planet Ghana - does not support planet cash donations for CH planet cash accounts.
https://donate-with-planet-oex50iyns-planetapp.vercel.app/?to=yucatan&step=donate - Yucatán Restoration - supports planet cash donations for all planet cash accounts.

Hide planetcash payment option if planetcash country is not supported for tax deductions

---

next.config.js
public/locales/en/common.json
src/Common/Types/QueryParamContextInterface.ts
src/Donations/Components/DonationsForm.tsx
src/Donations/Components/PaymentsForm.tsx
src/Donations/Micros/PlanetCashSelector.tsx
src/Donations/PaymentMethods/PaymentMethodTabs.tsx
src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx
src/Layout/QueryParamContext.tsx

Bugs fixed
1. Planetcash toggled on automatically after disabling - introduced by #447 
2. Planetcash switch turned on automatically after updating the amount or editing gift details
3. Resolves issues with paying into planetcash using native payments - payment failure, incorrect amount after visiting from the Add Balance button while on the project page - by making sure to refresh paymentRequest on every change to country, currency, amount.
Also:
1. Resolves an issue of jerky layout seen when Google Pay / Apple Pay buttons were present and amount was refreshed.
2. Enables login to vercel deployments with custom domains (e.g. applepay.pp.eco) without redirecting to the dynamic preview url. This is to be used for testing only, by setting the DISABLE_VERCEL_REDIRECT env to "true"

Fixes bugs with Planetcash selector

---

src/Common/Types/index.tsx
src/Donations/Components/DonationsForm.tsx
src/Layout/QueryParamContext.tsx
src/Utils/donationOptions.ts
src/Utils/projects/constants.ts

- Updates logic to display PlanetCash payment selector to allow more types of donations 
- Extract logic for determining Planet Cash eligibility into a utility function, simplifying the DonationsForm component.
- Adds constants related to project purposes and classifications for better clarity.
Updated logic - 
1. PlanetCash is allowed for one time donations to all projects with `purpose: "trees" | "conservation" | "funds"` with the exception of projects classified as `membership` or `endowment`.  
2. To use PlanetCash, the user must be logged in, and have a PlanetCash account for a country included in the taxDeductibleCountries for the project
3. The gift form should not be currently open (`isGift` and `giftDetails.recipientName = "")
For recurring donations, the planet cash selector, if …

Allow PlanetCash payments for more types of donations

---

public/locales/en/common.json
src/Donations/Micros/GiftForm.tsx

Implement validation to ensure the recipient name does not exceed 35 characters in the GiftForm. This includes error messaging for both required and length constraints.

Add validation for recipient name length in GiftForm

---

src/Donations/Components/DonationsForm.tsx
src/Donations/PaymentMethods/PaymentFunctions.ts

Include the X-Locale header in donation requests to support localization of certificates.

Add X-Locale header to donation POST requests

---

pages/index.tsx
src/Common/Types/QueryParamContextInterface.ts
src/Donations/Components/ContactsForm.tsx
src/Donations/Micros/Authentication.tsx
src/Donations/Micros/PaymentStatus/FailedDonation.tsx
src/Donations/PaymentMethods/PaymentFunctions.ts
src/Layout/QueryParamContext.tsx

1. Implement safeguards to prevent `isPackageWanted` from being included in the payload for the POST /app/donations call. 
2. Update the handling of contact details across various components to use a new method that sanitizes the data before updating the context state.
3. Improves logic to initialize `isPackageWanted` in `ContactsForm`. Updates the reset logic in `ContactsForm` to properly handle all possible states of `isPackageWanted` (`true`, `false`, `null`). When eligible for a package, defaults to true if no selection has been made yet, otherwise respects the user's choice.

Add safeguards for contact details in donation process

---

src/Donations/Micros/PlanetCashSignup.tsx

Remove 'US' from the list of allowed countries in the PlanetCashSignup component.

Remove 'US' from allowedCountries in PlanetCashSignup
