Plant-for-the-Planet-org/planet-donations

iframetest.html
next.config.js
src/Common/Types/index.tsx
src/Donations/Components/DonationsForm.tsx
src/Donations/Components/PaymentsForm.tsx
src/Donations/Micros/FrequencyOptions.tsx
src/Donations/PaymentMethods/PaymentFunctions.ts
src/Donations/PaymentMethods/PaymentMethodTabs.tsx
src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx
src/Layout/QueryParamContext.tsx
styles/donations.scss

Recurrent donations

---

pages/index.tsx
src/Layout/QueryParamContext.tsx

fixed trailing slash bug

---

pages/404.tsx
pages/_app.tsx
pages/index.tsx
src/Donations/Components/ContactsForm.tsx
src/Donations/Components/DonationsForm.tsx
src/Donations/Components/PaymentsForm.tsx
src/Donations/Components/SelectProject.tsx
src/Donations/Components/ThankYouComponent.tsx
src/Donations/Micros/Authentication.tsx
src/Donations/Micros/GiftForm.tsx
src/Donations/PaymentMethods/PaymentFunctions.ts
src/Donations/index.tsx
src/Layout/QueryParamContext.tsx

Changes-
- Syncing Browser back with in-app back button
@harshvitra

Syncing browser back

---

pages/_app.tsx

- Recycling of token
@harshvitra

recycling of token

---

src/Donations/Micros/TaxDeductionCountryModal.tsx

Alphabetically ordered tax deduction countries

Alphabetically ordered tax deduction countries

---

src/Donations/Micros/TaxDeductionCountryModal.tsx
src/Utils/countryUtils.ts

aphabetically ordered countries according to translations

---

pages/index.tsx

Fixes app crash on clicking donation ID
@harshvitra

removed treecount from state

---

cypress/integration/donations.spec.js
cypress/support/commands.js
src/Donations/index.tsx

Added test for reference donation. Checks if we can donate using ref ID.

Reference Donation Testing

---

src/Donations/Components/PaymentsForm.tsx

Fixes - addresses not being sent to stripe

Fixed stripe addresses

---

cypress/integration/languageTest.spec.js
src/Layout/Footer.tsx

Testing donations with different language.

Testing donations with different language.

---

cypress/integration/languageTest.spec.js
cypress/support/commands.js

- wait for language chooser to be loaded

fix language tests for slow networks

---

src/Layout/Footer.tsx

- changed footer links to pp.eco and using locales

changed footer links to pp.eco and using locales

---

pages/index.tsx

@sagararyal 
@sarveshpro 
Following behavior is on the develop branch.
The data should be same. 
Also test for other type of donations (e.g. Funding, Bouquet etc.)

fixed amount and quantity for direct payments via link

---

src/Donations/Micros/DonationTypes/BouquetDonations.tsx

Large donation amounts for bouquet projects issue fixed

---

public/robots.txt
src/Donations/index.tsx

SEO optimization

---

src/Layout/Header.tsx
styles/themeProperties.ts

https://medium.com/needmore-notes/using-system-fonts-for-web-apps-bf76d214a0e0

remove open sans and rely on system fonts

---

.github/workflows/cypress.yml
.github/workflows/eslint.yml
package-lock.json

- use latest npm version and package-lock.json format 2
- npm upgrade

use latest npm version and package-lock.json format 2

---

pages/index.tsx
src/Donations/Components/DonationsForm.tsx

Added meta data in Server-side props for better SEO
@norbertschuler

added meta-data in serverside props

---

public/locales/en/common.json
src/Donations/Components/DonationsForm.tsx
src/Donations/Components/PaymentsForm.tsx
src/Donations/PaymentMethods/PaymentFunctions.ts

fixed bank details Error

---

src/Layout/QueryParamContext.tsx

fix regex in testURL

---

pages/_app.tsx
src/Common/Types/index.tsx
src/Donations/Components/DonationsForm.tsx
src/Donations/Components/PaymentsForm.tsx
src/Donations/PaymentMethods/PaymentFunctions.ts
src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx
src/Layout/QueryParamContext.tsx

- Added paymentMethod as object provider
- Added prop types

Passing paymentMethod as object provider

---

.prettierrc.js
src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx

fixed the Amount changing issue in the stripe element.
https://planetde.slack.com/files/UTZSANCD7/F02QF090R9Q/screen_recording_2021-12-12_at_10.50.38_pm.mov
@norbertschuler @sarveshpro

added prettier, amount update in stripe element

---

pages/index.tsx

Fix URL being encoded in meta property twitter:url and og:url

FIX: remove url encoding in meta tags

---

src/Donations/Micros/DonationTypes/BouquetDonations.tsx
src/Donations/Micros/DonationTypes/FundingDonations.tsx
src/Layout/QueryParamContext.tsx

support query param units

---

public/locales/en/common.json

change thankyou text for funding donations

---

next.config.js
package-lock.json
package.json

Fixes #
- changed source maps generation

changed source maps generation

---

public/locales/en/common.json
src/Donations/Components/ContactsForm.tsx
src/Layout/QueryParamContext.tsx

Extra field for tax identification number is added for tax deduction country - Spain.

Tax Identifcation Number for Spain

---

src/Donations/Micros/Authentication.tsx

prevent app from crashing if app/profile fails

---

cypress/support/commands.js
src/Donations/Components/ContactsForm.tsx

When country spain is selected there appears tax identification field. So written test case for that.

Test case for tax Identification

---

src/Donations/Micros/PaymentStatus/ImageComponent.tsx
src/Donations/Micros/PaymentStatus/SuccessfulDonation.tsx
src/Donations/Micros/ShareOptions.tsx

Fixes fix download option on thankyou screen

fix download on thankyou screen

---

next-env.d.ts
package-lock.json
package.json
src/Donations/Components/DonationsForm.tsx
src/Donations/Micros/Authentication.tsx
src/Utils/getFormattedNumber.ts
src/Utils/tokenActions.ts

- token should get removed from query params after a successful login 
- this should not affect our normal donation flow

removed token after a successful login

---

src/Donations/Micros/DonationTypes/BouquetDonations.tsx
src/Donations/Micros/DonationTypes/FundingDonations.tsx

How to test:
1. Go to membership project (Project Id: proj_LOxkf5GYI054Fi0HcEUF3dKu)
2. try to change frequencies
3. the amount shouldn't change on the next step (contact details page)
4. after going back the default options should be selected (frequency: monthly and default payment option)
Note: In Membership project client checks if `costIsMonthly` is true, then multiply the amount with 12 if the the frequency is yearly.

fixed amount changing issue

---

pages/index.tsx
src/Common/Types/index.tsx
src/Donations/Components/ContactsForm.tsx
src/Donations/Components/DonationsForm.tsx
src/Donations/Components/PaymentsForm.tsx
src/Donations/Micros/DonationAmount.tsx
src/Donations/Micros/DonationTypes/BouquetDonations.tsx
src/Donations/Micros/DonationTypes/FundingDonations.tsx
src/Donations/Micros/FrequencyOptions.tsx
src/Donations/Micros/PaymentStatus/FailedDonation.tsx
src/Donations/PaymentMethods/NewPaypal.tsx
src/Donations/PaymentMethods/PaymentFunctions.ts
src/Donations/PaymentMethods/PaymentMethodTabs.tsx
src/Donations/index.tsx
src/Layout/QueryParamContext.tsx
src/Utils/common.ts

Changes made:
- New payment config implementation
What to test-
1. Test donation with all purposes and payment methods
2. Check the amount, quantity and frequency of API requests
3. Check direct donations also
Few Project Ids to test:
- Membership: proj_LOxkf5GYI054Fi0HcEUF3dKu
- Funding: proj_bFH0BU0Qw02RuetpQlLOMVYX
- Bouquet: proj_6x3GTD5cMRv0OeQAiIlJZ0Au
- Trees: proj_jIg2aW8I6RkLHwLcEZodh5Wq
- Conservation: proj_EZQ1nnevs6MoIjIzjlAFjU6M

implemented new payment config

---

src/Donations/Components/DonationsForm.tsx

Changed minimum amount to 2 euros instead of using it from the backend
How to test:
1. Go to any project and enter the custom amount/trees
2. If the calculated amount is less than 2 euros, user should see the error

Minimum amount to 2 euros

---

src/Donations/Micros/DonationTypes/BouquetDonations.tsx
src/Donations/Micros/DonationTypes/FundingDonations.tsx

Fixes custom quantity for conservation project after going back from Contacts screen to the Donation screen
projectId: proj_EZQ1nnevs6MoIjIzjlAFjU6M

fixed custom quantity for conservation project

---

public/locales/de/common.json
public/locales/en/common.json

Changed gift text for English and German

changed gift text for english and german

---

src/Donations/index.tsx

fixed tenant images

---

src/Donations/Micros/PlanetCashSelector.tsx
src/Layout/Header.tsx

This PR is a bug fix for planetCash and it also addresses issue #278

Allow user to add balance when pCash amount is not enough

---

src/Donations/Components/DonationsForm.tsx

Disable PlanetCash for project with purpose funds

Disable PlanetCash for project with purpose funds

---

public/locales/de/common.json
public/locales/en/common.json

Fixes #
-  adding missing resource for thank you screen

adding missing resource for thankyou screen

---

src/Donations/Components/DonationsForm.tsx

Disabled on behalf on Donation form screen

Disabled on behalf

---

public/locales/en/common.json

Renamed Donate with Pay

---

pages/index.tsx

This PR addresses https://github.com/Plant-for-the-Planet-org/planet-donations/issues/119

Disable unused routes to prevent redirection error

---

public/locales/en/common.json
src/Layout/Footer.tsx

Fixes #
- Localization - Add Translation to footer

Add Translation to footer

---

src/Donations/Components/PaymentStatus.module.scss
src/Donations/Components/PaymentStatus.tsx

- Fetch and set transfer details in the context
- Add loader while paymentStatus being set in context

Fetch and set transfer details in the context

---

pages/index.tsx
src/Donations/index.tsx
src/Layout/Footer.tsx

Fixes #
- Auto-switching the translation of Description of project

set translated description from paymentDetails api

---

pages/index.tsx

-  Fix showing blank screen after successful donation redirect

Fix showing blank screen after successful donation redirect

---

vercel.json

Adds headers to prevent iframe embeds

feat: add vercel.json headers to stop iframe embed

---

src/Donations/Micros/GiftForm.tsx

- Fix not appending gift in request payload bug

Fix not appending gift in request payload bug

---

pages/index.tsx
src/Donations/Components/DonationsForm.tsx
src/Donations/Micros/PlanetCashSignup.tsx
src/Layout/QueryParamContext.tsx

Fixes #
- Allow user to topup planetcash with queryToken

Allow user to topup planetcash with queryToken

---

src/Donations/Micros/PlanetCashSelector.tsx

Fixes #
- Deativate planetCash for monthly and yearly for gpay button

Deativate planetCash for monthly and yearly for gpay button

---

src/Donations/index.tsx
styles/donations.scss

Add back button for width<=767px
- Add back button which when clicked will redirect user to callback_url parameter in the url.

mobile view back button

---

public/locales/en/common.json
src/Donations/Components/SelectProject.tsx
styles/donations.scss

Fixes #
https://github.com/Plant-for-the-Planet-org/planet-donations/issues/315
- added scroll bar to donation forms.

add scrollbar to donation forms

---

src/Donations/Micros/PlanetCashSelector.tsx

When a PlanetCash account is active, display the currency/country of that account above the balance line.

display country/currency for active planet cash accounts.

---

public/locales/en/common.json
src/Donations/Components/PaymentsForm.tsx
src/Donations/Micros/PaymentStatus/TransferDetails.tsx

Fixes #
- Allow recurrent donations with bank transfer

Allow recurrent donations with bank transfer

---

src/Donations/index.tsx

The current donation site does not show project information on the context view 
Example (on staging - current version as on 29th March 2023)
https://donate-with-planet-hk50obpgd-planetapp.vercel.app/?context=don_zSEQhccF4YgNrwnkXD1BuxcT
This PR fixes this issue.

Shows project details on context page

---

.env.production
next.config.js
src/Layout/QueryParamContext.tsx

**Includes:**
#400 Updates config api to absolute URL

Release: Update Config URL

---

package-lock.json
package.json
pages/index.tsx
public/locales/de/common.json
public/locales/en/common.json
src/Common/Types/QueryParamContextInterface.ts
src/Common/Types/index.tsx
src/Donations/index.tsx
src/Layout/QueryParamContext.tsx
styles/donations.scss
styles/globals.scss

Issue: 
- Given the `approval` flag has been set in the backend, when a user makes a donation, then a check mark is shown behind the project name.
- Given the `Top Project` flag has also been set in the backend, when a user makes a donation, then they will see a label in the upper right corner of the image.

Top and verified projects (new)

---

package-lock.json
pages/index.tsx
src/Donations/Components/PaymentsForm.tsx
src/Donations/PaymentMethods/PaymentMethodTabs.tsx
src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx

- fix Stripe warning
- fix unknown tag warning
- fix component change while rendering

Smaller fixes collection

---

src/Common/Types/index.tsx
src/Donations/LeftPanel/Avatar.tsx
src/Donations/LeftPanel/ContactDetailsInfo.tsx
src/Donations/LeftPanel/GiftInfo.tsx
src/Donations/LeftPanel/LeftPanel.module.scss
src/Donations/LeftPanel/LeftPanelInfo.tsx
src/Donations/LeftPanel/OnBehalfInfo.tsx
src/Donations/LeftPanel/ProjectInfo.tsx
src/Donations/LeftPanel/ProjectTitle.tsx
src/Donations/LeftPanel/TransactionSummary.tsx
src/Donations/LeftPanel/VerifiedBadge.tsx
styles/donations.scss
styles/muiTheme.ts

Extracts code from `LeftPanelInfo` into smaller components, keeping the component display logic and layout within `LeftPanelInfo`.
**Components created:**
1. `Avatar`
2. `TransactionSummary`
3. `ProjectTitle`
a. `VerifiedBadge` child component 
5. `ProjectInfo`
6. `GiftInfo`
7. `OnBehalfInfo`
8. `ContactDetailsInfo`
**Other Changes:**
1. Moves most styles from global styles to modular styles
2. Move MUI style customizations from global styles to mui theme.
3. Separates logic for individual component display from html code for layout in `LeftPanelInfo`
4. Updates the donation link to use `/locale` instead of `?locale=`
5. Minor refinement of types
Pending

Simplifies LeftPanelInfo

---

package-lock.json
package.json
public/locales/en/common.json
src/Donations/LeftPanel/LeftPanel.module.scss
src/Donations/LeftPanel/LeftPanelInfo.tsx
src/Donations/LeftPanel/ProjectTitle.tsx
src/Donations/LeftPanel/TopProjectBadge.tsx
src/Donations/LeftPanel/VerifiedBadge.tsx

1. Replace top project badge
2. Reduce the size of verified icon
3. Restrict row count for Project Names
4. Adjust text pop-up on hover over Top Projects

style: update popup

---

public/locales/en/common.json
src/Common/Types/QueryParamContextInterface.ts
src/Common/Types/donation.d.ts
src/Common/Types/index.tsx
src/Donations/Components/ContactsForm.tsx
src/Donations/Components/DonationsForm.tsx
src/Donations/Components/PaymentsForm.tsx
src/Donations/PaymentMethods/PaymentFunctions.ts
src/Layout/QueryParamContext.tsx
src/Utils/countryUtils.ts
styles/donations.scss

1. Adds a welcome package consent toggle to the Contact Details Form for a specific project (proj_rLYELl1JpkT9sskba0sLPeKi) if the selected country (contact details) is an EU country (https://european-union.europa.eu/principles-countries-history/country-profiles_en / https://www.yourdictionary.com/articles/europe-country-codes). 
2. If the toggle is switched on while submitting the form, `metadata.welcomePackageStatus = draft` is sent while creating the donation

Membership Welcome Package

---

src/Layout/Footer.tsx

- fixed broken link to privacy policy in cookie note

replaced old not existing link to privacy policy

---

src/Donations/LeftPanel/LeftPanelInfo.tsx

Shows left panel info (avatar, name of user signing up) for pcash signup

Shows left panel info for pcash signup

---

package-lock.json
package.json

Updates planet-sdk to latest version - 0.1.34

Updates planet sdk

---

src/Utils/countryZipCode.js

Fixes https://planetfoundation.slack.com/archives/C02393H3GDC/p1703144455421289
@

fixed Lebanon zip code validation

---

src/Utils/countryZipCode.js

Release: Fix zip code validation Lebanon

---

public/locales/cs/common.json
public/locales/de/common.json
public/locales/en/common.json
public/locales/es/common.json
public/locales/fr/common.json
public/locales/it/common.json
public/locales/pt-BR/common.json
src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx

Changes misleading text "Use PayPal or Card" on Continue button in donate step

Updates Continue button text (Donate step)

---

public/locales/cs/common.json
public/locales/de/common.json
public/locales/en/common.json
public/locales/es/common.json
public/locales/fr/common.json
public/locales/it/common.json
public/locales/pt-BR/common.json
src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx
src/Utils/countryZipCode.js

Release: update text for Continue button (Donate step)

---

src/Donations/Micros/ShareOptions.tsx

Removes twitter handle in share text

Remove twitter handle in share text

---

src/Donations/Components/PaymentsForm.tsx
src/Donations/Micros/ShareOptions.tsx
src/Layout/Footer.tsx

- https://github.com/Plant-for-the-Planet-org/planet-donations/pull/463
- #465

Release 2024-06
